buildscript {
    ext {
        queryDslVersion = "5.0.0"
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id "org.sonarqube" version "5.1.0.4882"
    id 'jacoco'
    id 'com.epages.restdocs-api-spec' version '0.17.1'
    id 'org.hidetake.swagger.generator' version '2.18.2'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2', 'io.jsonwebtoken:jjwt-jackson:0.11.2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // query DSL 의존성 추가
    implementation "com.querydsl:querydsl-jpa:${queryDslVersion}:jakarta"
    annotationProcessor "com.querydsl:querydsl-apt:${queryDslVersion}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    // env 의존성 추가
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    // s3
    implementation 'software.amazon.awssdk:s3:2.30.16'

    // websocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // restdocs
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.17.1'

    // swagger-ui
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.0'

    // test container
    testImplementation 'org.testcontainers:junit-jupiter:1.18.0'
    testImplementation 'org.testcontainers:mysql:1.18.0'
}

// .env 파일 읽기
def loadEnvProperties() {
    def envFile = file('.env')
    def props = new Properties()
    if (envFile.exists()) {
        envFile.withReader('UTF-8') { reader ->
            props.load(reader)
        }
    }
    return props
}

def envProps = loadEnvProperties()
envProps.each { key, value ->
    project.ext."$key" = value
}

//-- Query DSL generated path --//
def querydslDir = "src/main/generated"

sourceSets {
    main.java.srcDirs += [querydslDir]
}

tasks.withType(JavaCompile) {
    options.getGeneratedSourceOutputDirectory().set(file(querydslDir))
}

clean.doLast {
    file(querydslDir).deleteDir()
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
    }
}

def loadPropertiesFile(filePath) {
    def props = new Properties()
    file(filePath).withInputStream {
        props.load(it)
    }
    return props
}

// 로컬에서만 사용. 커밋할 때 주석처리하고, 로컬에서 실행할 때는 아래 System.getenv를 주석처리
def sonarToken = project.ext.SONARQUBETOKEN

//def sonarToken = System.getenv("SONARQUBETOKEN")

sonarqube {
    properties {
        property "sonar.host.url", "http://localhost:9000"
        property "sonar.token", sonarToken
        property "sonar.projectKey", "swap-it"
        property "sonar.sources", "src"
        property "sonar.language", "java"
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.test.inclusions", "**/*Test.java"
        property 'sonar.exclusions', '**/test/**, **/resources/**, **/*Application.java, **/generated/**, **/config/**, **/common/**'
        property 'sonar.coverage.jacoco.xmlReportPaths', layout.buildDirectory.dir("reports/jacoco/test/jacocoTestReport.xml").get().asFile
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

ext {
    snippetsDir = file('build/generated-snippets')
}

// 로컬에서만 사용. 커밋할 때 주석처리하고, 로컬에서 실행할 때는 아래 System.getenv를 주석처리
def localServerUrl = project.ext.LOCAL_SERVER_URL
def serverUrl = project.ext.SERVER_URL

//def serverUrl = System.getenv("SERVER_URL")

openapi3 {
    server = localServerUrl
    title = "Swap It API 문서"
    description = "Spring REST Docs with SwaggerUI."
    version = "0.0.1"
    outputFileNamePrefix = 'open-api-3.0.1'
    format = 'json'
    outputDirectory = 'build/resources/main/static/docs'
}

tasks.whenTaskAdded { task ->
    if (task.name == 'openapi3') {
        task.dependsOn(test)
    }
    if (task.name == 'addSecurityToOpenApi') {
        task.dependsOn('openapi3')
    }
}

tasks.register('addSecurityToOpenApi') {
    doLast {
        def swaggerUIFile = file("${openapi3.outputDirectory}/${openapi3.outputFileNamePrefix}.${openapi3.format}")

        if (swaggerUIFile.exists()) {
            try {
                def jsonText = swaggerUIFile.text

                def jsonSlurper = new groovy.json.JsonSlurper()
                def jsonContent = jsonSlurper.parseText(jsonText)

                if (!jsonContent.containsKey('components')) {
                    jsonContent.put('components', [:])
                } else {
                    println "Using existing 'components' object"
                }

                def components = jsonContent.components
                components.put('securitySchemes', [
                        'APIKey': [
                                'type': 'apiKey',
                                'name': 'Authorization',
                                'in'  : 'header'
                        ]
                ])

                jsonContent.put('security', [['APIKey': []]])

                def jsonBuilder = new groovy.json.JsonBuilder(jsonContent)
                def updatedJson = jsonBuilder.toPrettyString()
                swaggerUIFile.text = updatedJson
            } catch (Exception e) {
                e.printStackTrace()
            }
        } else {
            println "ERROR: OpenAPI file not found at ${swaggerUIFile.absolutePath}"
        }
    }
}

tasks.withType(GenerateSwaggerUI) {
    dependsOn 'addSecurityToOpenApi'
}

bootJar {
    dependsOn tasks.withType(GenerateSwaggerUI)
}