spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      instance-profile: true  # IAM Role 사용

    cloudfront:
      url: ${CLOUDFRONT_URL}

firebase:
  config-env: ${FIREBASE_CONFIG}

logging:
  level:
    com.example.swapit: debug
    org.springframework.messaging.simp: debug